//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTransactionID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessTransactionID()
        {
            this.EPCISEvent_BusinessTransactionID = new HashSet<EPCISEvent_BusinessTransactionID>();
        }
    
        public long ID { get; set; }
        public string URN { get; set; }
        public long BusinessTransactionTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_BusinessTransactionID> EPCISEvent_BusinessTransactionID { get; set; }
        public virtual Vocabulary Vocabulary { get; set; }
    }
}
