//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPCISEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPCISEvent()
        {
            this.EPCISEvent_BusinessTransactionID = new HashSet<EPCISEvent_BusinessTransactionID>();
            this.EPCISEvent_DocumentHeader = new HashSet<EPCISEvent_DocumentHeader>();
            this.EPCISEvent_EPC = new HashSet<EPCISEvent_EPC>();
            this.EPCISEvent_QuantityElement = new HashSet<EPCISEvent_QuantityElement>();
            this.EPCISEvent_SourceDestination = new HashSet<EPCISEvent_SourceDestination>();
            this.EPCISEvent_Value = new HashSet<EPCISEvent_Value>();
            this.EPCISEvent_Vocabulary = new HashSet<EPCISEvent_Vocabulary>();
            this.EPCISEvent_TransformationID = new HashSet<EPCISEvent_TransformationID>();
        }
    
        public long ID { get; set; }
        public long ClientID { get; set; }
        public System.DateTime EventTime { get; set; }
        public System.DateTime RecordTime { get; set; }
        public System.DateTimeOffset EventTimeZoneOffset { get; set; }
        public string XmlRepresentation { get; set; }
        public bool Error { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_BusinessTransactionID> EPCISEvent_BusinessTransactionID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_DocumentHeader> EPCISEvent_DocumentHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_EPC> EPCISEvent_EPC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_QuantityElement> EPCISEvent_QuantityElement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_SourceDestination> EPCISEvent_SourceDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_Value> EPCISEvent_Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_Vocabulary> EPCISEvent_Vocabulary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_TransformationID> EPCISEvent_TransformationID { get; set; }
        public virtual Vocabulary Vocabulary { get; set; }
    }
}
