//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuantityElement()
        {
            this.EPCISEvent_QuantityElement = new HashSet<EPCISEvent_QuantityElement>();
        }
    
        public long ID { get; set; }
        public long EPCClassID { get; set; }
        public double Quantity { get; set; }
        public string UOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_QuantityElement> EPCISEvent_QuantityElement { get; set; }
        public virtual Vocabulary Vocabulary { get; set; }
    }
}
