//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepositoryContext : DbContext
    {
        public RepositoryContext()
            : base("name=RepositoryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Time> Time { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Schedule_Part> Schedule_Part { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Trigger> Trigger { get; set; }
        public virtual DbSet<EPCISDocumentHeader> EPCISDocumentHeader { get; set; }
        public virtual DbSet<BusinessTransactionID> BusinessTransactionID { get; set; }
        public virtual DbSet<EPC> EPC { get; set; }
        public virtual DbSet<EPCISEvent> EPCISEvent { get; set; }
        public virtual DbSet<EPCISEvent_BusinessTransactionID> EPCISEvent_BusinessTransactionID { get; set; }
        public virtual DbSet<EPCISEvent_DocumentHeader> EPCISEvent_DocumentHeader { get; set; }
        public virtual DbSet<EPCISEvent_EPC> EPCISEvent_EPC { get; set; }
        public virtual DbSet<EPCISEvent_QuantityElement> EPCISEvent_QuantityElement { get; set; }
        public virtual DbSet<EPCISEvent_SourceDestination> EPCISEvent_SourceDestination { get; set; }
        public virtual DbSet<EPCISEvent_TransformationID> EPCISEvent_TransformationID { get; set; }
        public virtual DbSet<EPCISEvent_Value> EPCISEvent_Value { get; set; }
        public virtual DbSet<EPCISEvent_Value_Datetime> EPCISEvent_Value_Datetime { get; set; }
        public virtual DbSet<EPCISEvent_Value_Hierarchy> EPCISEvent_Value_Hierarchy { get; set; }
        public virtual DbSet<EPCISEvent_Value_Numeric> EPCISEvent_Value_Numeric { get; set; }
        public virtual DbSet<EPCISEvent_Value_String> EPCISEvent_Value_String { get; set; }
        public virtual DbSet<EPCISEvent_Vocabulary> EPCISEvent_Vocabulary { get; set; }
        public virtual DbSet<QuantityElement> QuantityElement { get; set; }
        public virtual DbSet<TransformationID> TransformationID { get; set; }
        public virtual DbSet<Value_String> Value_String { get; set; }
        public virtual DbSet<EPCISEvent_Queue> EPCISEvent_Queue { get; set; }
        public virtual DbSet<EPCISMasterData_Queue> EPCISMasterData_Queue { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<AttributeType> AttributeType { get; set; }
        public virtual DbSet<Vocabulary> Vocabulary { get; set; }
        public virtual DbSet<VocabularyAttribute> VocabularyAttribute { get; set; }
        public virtual DbSet<VocabularyChildren> VocabularyChildren { get; set; }
        public virtual DbSet<VocabularyType> VocabularyType { get; set; }
        public virtual DbSet<VocabularyType_Client> VocabularyType_Client { get; set; }
        public virtual DbSet<HELP> HELP { get; set; }
    }
}
