//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public string ID { get; set; }
        public string Value { get; set; }
        public long ClientID { get; set; }
    
        public virtual Vocabulary Vocabulary { get; set; }
    }
}
