//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Schedule = new HashSet<Schedule>();
            this.Trigger = new HashSet<Trigger>();
        }
    
        public long ID { get; set; }
        public long ClientID { get; set; }
        public string Username { get; set; }
        public string Subscription1 { get; set; }
        public string Query { get; set; }
        public string DestinationEndpoint { get; set; }
        public System.DateTime InitialRecordTime { get; set; }
        public System.DateTime LastRecordTime { get; set; }
        public bool ReportIfEmpty { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Vocabulary Vocabulary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trigger> Trigger { get; set; }
    }
}
