//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qbq.EPCIS.EF.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vocabulary()
        {
            this.Settings = new HashSet<Settings>();
            this.Subscription = new HashSet<Subscription>();
            this.BusinessTransactionID = new HashSet<BusinessTransactionID>();
            this.EPCISEvent = new HashSet<EPCISEvent>();
            this.EPCISEvent_SourceDestination = new HashSet<EPCISEvent_SourceDestination>();
            this.EPCISEvent_SourceDestination1 = new HashSet<EPCISEvent_SourceDestination>();
            this.EPCISEvent_Value = new HashSet<EPCISEvent_Value>();
            this.EPCISEvent_Value1 = new HashSet<EPCISEvent_Value>();
            this.EPCISEvent_Vocabulary = new HashSet<EPCISEvent_Vocabulary>();
            this.QuantityElement = new HashSet<QuantityElement>();
            this.AttributeType = new HashSet<AttributeType>();
            this.Vocabulary1 = new HashSet<Vocabulary>();
            this.VocabularyAttribute = new HashSet<VocabularyAttribute>();
            this.VocabularyChildren = new HashSet<VocabularyChildren>();
            this.VocabularyChildren1 = new HashSet<VocabularyChildren>();
            this.VocabularyType_Client = new HashSet<VocabularyType_Client>();
        }
    
        public long ID { get; set; }
        public long ClientID { get; set; }
        public long VocabularyTypeID { get; set; }
        public string URN { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settings> Settings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessTransactionID> BusinessTransactionID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent> EPCISEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_SourceDestination> EPCISEvent_SourceDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_SourceDestination> EPCISEvent_SourceDestination1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_Value> EPCISEvent_Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_Value> EPCISEvent_Value1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPCISEvent_Vocabulary> EPCISEvent_Vocabulary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityElement> QuantityElement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeType> AttributeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vocabulary> Vocabulary1 { get; set; }
        public virtual Vocabulary Vocabulary2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyAttribute> VocabularyAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyChildren> VocabularyChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyChildren> VocabularyChildren1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocabularyType_Client> VocabularyType_Client { get; set; }
        public virtual VocabularyType VocabularyType { get; set; }
    }
}
