CREATE TABLE [Event].[EPC] (
    [ID]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [URN] NVARCHAR (512) NOT NULL,
    CONSTRAINT [PK_EPC] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EPC]
    ON [Event].[EPC]([URN] ASC);

